 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

2. Given a NumPy array 'arr', check if its data type is float64. 

In [7]:
arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [2]:
import numpy as np

# Create a NumPy array of complex numbers with data type complex128
arr = np.array([1+2j, 3-4j, 5+6j], dtype=complex)

print("NumPy array 'arr':", arr)
print("Data type of the array:", arr.dtype)

NumPy array 'arr': [1.+2.j 3.-4.j 5.+6.j]
Data type of the array: complex128


 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [4]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)

arr_float32 = arr.astype(np.float32)

In [6]:
print(arr_float32)
print(arr_float32.dtype)

[1. 2. 3. 4. 5.]
float32


 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [7]:
arr = np.array([1.08527852, 2.82278799, 3.91424879], dtype=np.float64)

arr_float32 = arr.astype(np.float32)

In [8]:
print(arr_float32)
print(arr_float32.dtype)

[1.0852785 2.822788  3.9142487]
float32


6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [21]:
sample_array = np.array([[1, 2, 3], [4, 5, 6]])

In [83]:
print(sample_array.shape)
print(sample_array.size)
print(sample_array.dtype)

(2, 3)
6
int64


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [26]:
def array_dimension(arr):
    return arr.ndim
if __name__ == "__main__":
    one_dimensional_array = np.array([1, 2, 3, 4, 5])
    two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])
    three_dimensional_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

    one_dim_count = array_dimension(one_dimensional_array)
    two_dim_count = array_dimension(two_dimensional_array)
    three_dim_count = array_dimension(three_dimensional_array)

    print(f"One-dimensional array: {one_dim_count} dimension")
    print(f"Two-dimensional array: {two_dim_count} dimensions")
    print(f"Three-dimensional array: {three_dim_count} dimensions")

One-dimensional array: 1 dimension
Two-dimensional array: 2 dimensions
Three-dimensional array: 3 dimensions


 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
size in bytes.

In [27]:
def item_size_info(array: np.ndarray) -> tuple:
    item_size = array.itemsize
    total_size = item_size * array.size
    return item_size, total_size

array = np.array([1, 2, 3, 4, 5], dtype=np.int64)
item_size, total_size = item_size_info(array)

print(f"Item size: {item_size} bytes")
print(f"Total size: {total_size} bytes")

Item size: 8 bytes
Total size: 40 bytes


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [28]:
def array_strides(array: np.ndarray) -> tuple:
    return array.strides

array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
strides = array_strides(array)

print(f"Strides: {strides}")

Strides: (24, 8)


 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
and strides of the array

In [31]:
def shape_stride_relationship(array: np.ndarray):
    return array.shape, array.strides

array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
shape, strides = shape_stride_relationship(array)

print(f"Shape: {shape}")
print(f"Strides: {strides}")

Shape: (2, 3)
Strides: (24, 8)


 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
zeros with `n` elements

In [33]:
def create_zeros_array(n: int) :
    return np.zeros(n)

n = 5
array = create_zeros_array(n)
array

array([0., 0., 0., 0., 0.])

 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
NumPy array filled with ones of size `rows x cols`

In [79]:
def create_ones_matrix(rows: int, cols: int):
    return np.ones((rows, cols))

rows = 3
cols = 4
matrix = create_ones_matrix(rows, cols)
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
`step`.

In [78]:
def generate_range_array(start: int, stop: int, step: int):
    return np.arange(start, stop, step)

start = 1
stop = 10
step = 2
array = generate_range_array(start, stop, step)
array

array([1, 3, 5, 7, 9])

 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
(inclusive)

In [77]:
def generate_linear_space(start: float, stop: float, num: int):
    return np.linspace(start, stop, num)

start = 1.0
stop = 10.0
num = 5
array = generate_linear_space(start, stop, num)
array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
identity matrix of size `n x n` using `numpy.eye`

In [76]:
def create_identity_matrix(n: int):
    return np.eye(n)

n = 5
matrix = create_identity_matrix(n)
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

16. Write a function that takes a Python list and converts it into a NumPy array

In [75]:
def list_to_numpy_array(input_list: list):
    return np.array(input_list)

input_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(input_list)
numpy_array

array([1, 2, 3, 4, 5])

 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
same data

In [43]:
original_array = np.array([1, 2, 3, 4, 6])
view_array = original_array.view()
original_array[0] = 10

In [44]:
print("Original Array:", original_array)
print("View Array:", view_array)

Original Array: [10  2  3  4  6]
View Array: [10  2  3  4  6]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis

In [48]:
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

In [74]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concatenated_array = concatenate_arrays(arr1, arr2, axis=0)
concatenated_array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concatenated_array = concatenate_arrays(arr1, arr2, axis=1)
concatenated_array

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

 19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
 concatenate`

In [71]:
# Create two NumPy arrays with different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

# Concatenate them horizontally 
concatenated_array = np.concatenate((arr1, arr2), axis=1)
concatenated_array

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

 20. Write a function that vertically stacks multiple NumPy arrays given as a list

In [70]:
def vertical_stack(arrays):
    return np.vstack(arrays)

arrays = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

stacked_array = vertical_stack(arrays)
stacked_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
with a given step size.

In [69]:
def create_array(start, end, step):
    return np.arange(start, end + 1, step)

array = create_array(1, 10, 2)
array

array([1, 3, 5, 7, 9])

 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
(inclusive)

In [68]:
def generate_array():
    return np.linspace(0, 1, 10)

array = generate_array()

array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
1000 (inclusive)

In [67]:
def generate_array():
    return np.logspace(np.log10(1), np.log10(1000), 5)

array = generate_array()

array

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
are random integers between 1 and 100

In [66]:
import pandas as pd
array = np.random.randint(1, 101, size = (5, 3))
df = pd.DataFrame(array, columns = ["Column1", "Column2", "Column3"])
df

Column1  Column2  Column3
0       48       82       72
1       29       49       27
2       42       28       69
3       67       20       22
4       71       67       55

 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
with zeros. Use NumPy operations within the Pandas DataFrame

26. Access the 3rd element from the given NumPy array.                   
 arr = np.array([10, 20, 30, 40, 50])

In [2]:
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
third_element

30

 27. Retrieve the element at index (1, 2) from the 2D NumPy array.             
 arr_2d = np.array([[1, 2, 3],

 [4, 5, 6],

 [7, 8, 9]])

In [3]:
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

element = arr_2d[1, 2]
element

6

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.           
 arr = np.array([3, 8, 2, 10, 5, 7])

In [4]:
arr = np.array([3, 8, 2, 10, 5, 7])
greater_than_five = arr[arr > 5]

greater_than_five

array([ 8, 10,  7])

 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.       
 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr[2:6] 

sliced_array

array([3, 4, 5, 6])

30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.         
 arr_2d = np.array([[1, 2, 3],

 [4, 5, 6],

 [7, 8, 9]])

In [6]:
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]
sub_array

array([[2, 3],
       [5, 6]])

31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
provided in another array.

In [7]:
def extract_elements(arr, indices):
    return arr[indices[:, 0], indices[:, 1]]

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 0], [1, 1], [2, 2]])
print(extract_elements(arr, indices)) 

[1 5 9]


 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
boolean indexing.

In [8]:
def filter_elements(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 2, 3, 4, 5, 6])
threshold = 3
print(filter_elements(arr, threshold))  

[4 5 6]


 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
separate arrays for each dimension.

In [9]:
def extract_elements(arr, x_indices, y_indices, z_indices):
    return arr[x_indices, y_indices, z_indices]
arr = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 2, 0])
z_indices = np.array([0, 1, 2])

print(extract_elements(arr, x_indices, y_indices, z_indices))  

[ 4 17 21]


 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied 
using boolean indexing.

In [10]:
def elements_satisfying_conditions(arr, condition1, condition2):
    return arr[(arr > condition1) & (arr < condition2)]
arr = np.array([1, 2, 3, 4, 5, 6])
print(elements_satisfying_conditions(arr, 2, 5)) 

[3 4]


 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
in separate arrays.

In [11]:
def extract_elements(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

print(extract_elements(arr, row_indices, col_indices))  

[2 6 7]


 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [16]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
result = arr + 5

print("Original Array:")
print(arr)
print("\nArray after adding 5:")
print(result)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after adding 5:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
corresponding element in arr1 using NumPy broadcasting.

In [30]:
arr1 = np.array([[1, 2, 3]])  # Shape (1, 3)
arr2 = np.array([[4, 5, 6, 7],  # Shape (3, 4)
                  [8, 9, 1, 1],
                  [2, 3, 4, 5]])
print(arr1.shape)
print(arr2.shape)


print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult of multiplication:")
print(result)

(1, 3)
(3, 4)
Array arr1:
[[1 2 3]]

Array arr2:
[[4 5 6 7]
 [8 9 1 1]
 [2 3 4 5]]

Result of multiplication:
[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
NumPy broadcasting.

In [35]:
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7],  # Shape (4, 3)
                  [8, 9, 10],
                  [11, 12, 13],
                  [14, 15, 16]])
print(arr1.shape)
print(arr2.shape)

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult of addition:")
print(result)

(1, 4)
(4, 3)
Array arr1:
[[1 2 3 4]]

Array arr2:
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]

Result of addition:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
broadcasting.

In [38]:
arr1 = np.array([[1],   # Shape (3, 1)
                  [2],
                  [3]])

arr2 = np.array([[4, 5, 6]])  # Shape (1, 3)
print(arr1.shape)
print(arr2.shape)

result = arr1 + arr2

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult of addition:")
print(result)

(3, 1)
(1, 3)
Array arr1:
[[1]
 [2]
 [3]]

Array arr2:
[[4 5 6]]

Result of addition:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
broadcasting. Handle the shape incompatibility.

In [40]:
arr1 = np.array([[1, 2, 3],  # Shape (2, 3)
                  [4, 5, 6]])

arr2 = np.array([[7, 8],  # Shape (2, 2)
                  [9, 10]])
arr2 = np.repeat(arr2, 3, axis=1)

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult of multiplication:")
print(result)

Array arr1:
[[1 2 3]
 [4 5 6]]

Array arr2:
[[ 7  7  7  8  8  8]
 [ 9  9  9 10 10 10]]

Result of multiplication:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


 41. Calculate column-wise mean for the given array:              
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [41]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

column_means = np.mean(arr, axis=0)

print(arr)
print("\nColumn-wise means:")
print(column_means)

[[1 2 3]
 [4 5 6]]

Column-wise means:
[2.5 3.5 4.5]


 42. Find maximum value in each row of the given array:            
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [42]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

row_maxima = np.max(arr, axis=1)

print("Array:")
print(arr)
print("\nMaximum value in each row:")
print(row_maxima)

Array:
[[1 2 3]
 [4 5 6]]

Maximum value in each row:
[3 6]


 43. For the given array, find indices of maximum value in each column.          
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [44]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Find the indices of maximum values in each column
col_max_indices = np.argmax(arr, axis=0)

print("Array:")
print(arr)
print("\nIndices of maximum values in each column:")
print(col_max_indices)

Array:
[[1 2 3]
 [4 5 6]]

Indices of maximum values in each column:
[1 1 1]


 44. For the given array, apply custom function to calculate moving sum along rows.       
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(a, n=2):
    return np.array([sum(a[i:i+n]) for i in range(len(a)-n+1)])

result = np.apply_along_axis(moving_sum, 1, arr)

print(result)

[[ 3  5]
 [ 9 11]]


 45. In the given array, check if all elements in each column are even.         
 arr = np.array([[2, 4, 6], [3, 5, 7]])

In [49]:
arr = np.array([[2, 4, 6], 
                [3, 5, 7]])

# Check if all elements in each column are even
are_all_even = np.all(arr % 2 == 0, axis=0)

print("Array:")
print(arr)
print("\nAre all elements in each column even?")
print(are_all_even)

Array:
[[2 4 6]
 [3 5 7]]

Are all elements in each column even?
[False False False]


46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
reshaped matrix.            
 original_array = np.array([1, 2, 3, 4, 5, 6])

In [50]:
original_array = np.array([1, 2, 3, 4, 5, 6])


m = 2  # Number of rows
n = 3  # Number of columns

reshaped_matrix = original_array.reshape(m, n)

print("Original Array:")
print(original_array)
print("\nReshaped Matrix:")
print(reshaped_matrix)

Original Array:
[1 2 3 4 5 6]

Reshaped Matrix:
[[1 2 3]
 [4 5 6]]


 47. Create a function that takes a matrix as input and returns the flattened array.          
 input_matrix = np.array([[1, 2, 3], [4, 5, 6]]) 

In [51]:
def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)

print(flattened_array)

[1 2 3 4 5 6]


 48. Write a function that concatenates two given arrays along a specified axis.          
 array1 = np.array([[1, 2], [3, 4]])

 array2 = np.array([[5, 6], [7, 8]])

In [53]:
def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result = concatenate_arrays(array1, array2, axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


 49. Create a function that splits an array into multiple sub-arrays along a specified axis.     
 original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [54]:
def split_array(original_array, num_subarrays, axis):
    return np.split(original_array, num_subarrays, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result = split_array(original_array, 3, axis=0)
print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


 50. Write a function that inserts and then deletes elements from a given array at specified indices.            
 original_array = np.array([1, 2, 3, 4, 5])

 indices_to_insert = [2, 4]

 values_to_insert = [10, 11]

 indices_to_delete = [1, 3]

In [56]:
def insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    new_array = original_array.copy()
    new_array = np.insert(new_array, indices_to_insert, values_to_insert)
    new_array = np.delete(new_array, indices_to_delete)
    return new_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result)

[ 1 10  4 11  5]


 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`.

In [60]:
arr1 = np.random.randint(0, 10, size=(3, 5))
arr2 = np.arange(1, 11).reshape(2, 5)  

arr2 = np.tile(arr2, (2, 1))


print("Array arr1 (random integers):")
print(arr1)
print("\nArray arr2 (integers from 1 to 10):")
print(arr2)
print("\nResult of element-wise addition:")
print(result)

Array arr1 (random integers):
[[7 0 3 6 8]
 [6 1 4 9 3]
 [4 7 7 9 9]]

Array arr2 (integers from 1 to 10):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Result of element-wise addition:
[ 1 10  4 11  5]


52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [3]:
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

result = arr1 - arr2

print("Array arr1 (integers from 10 to 1):")
print(arr1)
print("\nArray arr2 (integers from 1 to 10):")
print(arr2)
print("\nResult of element-wise subtraction (arr1 - arr2):")
print(result)

Array arr1 (integers from 10 to 1):
[10  9  8  7  6  5  4  3  2  1]

Array arr2 (integers from 1 to 10):
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction (arr1 - arr2):
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
Perform element-wise multiplication between `arr1` and `arr2`.

In [4]:
arr1 = np.random.randint(0, 10, size=(3, 5))
arr2 = np.arange(1, 6).reshape(1, 5)

arr2 = np.repeat(arr2, 3, axis=0) 

result = arr1 * arr2

print("Array arr1 (random integers):")
print(arr1)
print("\nArray arr2 (integers from 1 to 5):")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result)

Array arr1 (random integers):
[[4 9 4 9 0]
 [0 7 8 8 7]
 [1 6 2 0 2]]

Array arr2 (integers from 1 to 5):
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]

Result of element-wise multiplication:
[[ 4 18 12 36  0]
 [ 0 14 24 32 35]
 [ 1 12  6  0 10]]


 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
to 5. Perform element-wise division of `arr1` by `arr2`.

In [5]:
arr1 = np.arange(1, 6) * 2
arr2 = np.arange(1, 6)

result = arr1 / arr2

print("Array arr1 (even integers from 2 to 10):")
print(arr1)
print("\nArray arr2 (integers from 1 to 5):")
print(arr2)
print("\nResult of element-wise division (arr1 / arr2):")
print(result)

Array arr1 (even integers from 2 to 10):
[ 2  4  6  8 10]

Array arr2 (integers from 1 to 5):
[1 2 3 4 5]

Result of element-wise division (arr1 / arr2):
[2. 2. 2. 2. 2.]


 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [6]:
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]

result = arr1 ** arr2

print("Array arr1 (integers from 1 to 5):")
print(arr1)
print("\nArray arr2 (reversed):")
print(arr2)
print("\nResult of element-wise exponentiation (arr1 ** arr2):")
print(result)

Array arr1 (integers from 1 to 5):
[1 2 3 4 5]

Array arr2 (reversed):
[5 4 3 2 1]

Result of element-wise exponentiation (arr1 ** arr2):
[ 1 16 27 16  5]


 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
 arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [8]:
def count_substring(arr, substring):
    return np.sum(np.core.defchararray.find(arr, substring)!= -1)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

result = count_substring(arr, substring)
result

3

 57. Write a function that extracts uppercase characters from a NumPy array of strings.
 arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
 arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [13]:
def extract_uppercase(arr):
    return np.array([''.join(filter(str.isupper, s)) for s in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

result = extract_uppercase(arr)
result

array(['H', 'W', 'OAI', 'GPT'], dtype='<U3')

58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [14]:
def replace_substring(arr, old, new):
    return np.core.defchararray.replace(arr, old, new)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old = 'apple'
new = 'ango'

result = replace_substring(arr, old, new)
result

array(['ango', 'banana', 'grape', 'pineango'], dtype='<U8')

 59. Write a function that concatenates strings in a NumPy array element-wise.
 arr1 = np.array(['Hello', 'World'])

 arr2 = np.array(['Open', 'AI'])

In [15]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = np.core.defchararray.add(arr1, arr2)
result

array(['HelloOpen', 'WorldAI'], dtype='<U9')

 60. Write a function that finds the length of the longest string in a NumPy array.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [20]:
def longest_string_length(arr):
    return max(len(s) for s in arr)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
max_length = longest_string_length(arr)

print("Length of the longest string:", max_length)


Length of the longest string: 9


 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
standard deviation of the dataset using NumPy's functions.

In [21]:
data = np.random.randint(1, 1001, size=100)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

print("Dataset:", data)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Dataset: [ 94 290 811 566 742 501 978 216 506 351 776 446 279 963 163 926 579 906
 130 399 145 533  10 576 738  19 633 324  44 828 166 301 159 485 135 110
 448 214 644 699 522 903 181 658 712 103 655  57   6  22 990  45 758 742
 629 623 400 956 491 725 627 754 168 291 758 626 178 672 510 216 769 292
 932 213 105 498 361 544 761 645 471  38  43 357 177 691 715 243 986 971
 906 356 738  66 651 655 375  76 338 374]
Mean: 471.58
Median: 494.5
Variance: 84070.32359999999
Standard Deviation: 289.948829278547


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
dataset.

In [22]:
data = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("Dataset:", data)
print("\n25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Dataset: [32 22 68 18 66 23 51 45  5 60 69 69 94  5 80 56 97 71 78 45 95 92 88 72
 61 83 15 79 57 12 35 65 45 26 70 45 28 11 82 20 68 84 30 46 76 40 19 42
 11 65]

25th Percentile: 28.5
75th Percentile: 71.75


 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
arrays using NumPy's `corrcoef` function.

In [23]:
array1 = np.random.rand(50)
array2 = np.random.rand(50)

correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Array 1:", array1)
print("\nArray 2:", array2)
print("\nCorrelation Coefficient:", correlation_coefficient)

Array 1: [0.33814749 0.86350576 0.27492344 0.80637336 0.81493984 0.11838607
 0.95077422 0.92305008 0.58696921 0.84419728 0.37609441 0.92610882
 0.11016844 0.54333251 0.01264657 0.52650767 0.60596926 0.11967083
 0.32969946 0.47291513 0.99516552 0.60766191 0.09380194 0.24284369
 0.58171329 0.27231439 0.65363847 0.19213321 0.7712161  0.44273671
 0.65613713 0.3237319  0.53705331 0.64683576 0.44531438 0.64508176
 0.62770071 0.32952364 0.080275   0.35790893 0.0102857  0.94504745
 0.05839183 0.88368308 0.72327004 0.1222047  0.38509505 0.26644031
 0.32997057 0.69555941]

Array 2: [0.33259007 0.87529881 0.05105416 0.50674725 0.56941979 0.56206368
 0.44281803 0.43933814 0.61349003 0.53806051 0.89443417 0.34848382
 0.84022448 0.57514019 0.39985602 0.38546778 0.48358913 0.56588329
 0.90047505 0.04701391 0.78581009 0.48720892 0.09877797 0.26710158
 0.34572834 0.14514868 0.3715301  0.05355492 0.67380791 0.23410985
 0.37480632 0.35743762 0.15053824 0.23360302 0.8805702  0.54577465
 0.9358102  0.05235

 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [24]:
matrix1 = np.random.rand(3, 4)
matrix2 = np.random.rand(4, 2)

result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nResult:\n", result)

Matrix 1:
 [[0.66285875 0.19543552 0.3538513  0.46730918]
 [0.96010428 0.55419677 0.09814723 0.26206934]
 [0.79646924 0.57876411 0.49488252 0.90065844]]

Matrix 2:
 [[0.45350021 0.71954551]
 [0.67074342 0.24920726]
 [0.28072717 0.13123503]
 [0.98892376 0.12132851]]

Result:
 [[0.99316249 0.6287966 ]
 [1.09385051 0.87362542]
 [1.77901069 0.89154956]]


 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
percentiles along with the first and third quartiles.

In [25]:
data = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(data, 10)
median = np.percentile(data, 50)  # 50th percentile
percentile_90 = np.percentile(data, 90)

first_quartile = np.percentile(data, 25)  # 25th percentile
third_quartile = np.percentile(data, 75)   # 75th percentile

print("Dataset:", data)
print("\n10th Percentile:", percentile_10)
print("50th Percentile (Median):", median)
print("90th Percentile:", percentile_90)
print("First Quartile (Q1):", first_quartile)
print("Third Quartile (Q3):", third_quartile)

Dataset: [376  61 502 309 365 363 848 765 350 194 363  30 971 795 666 150 654 608
 840 919 590 494 723 160 927 725 410 392 526 651 484 588 845 621 472 647
  17 193 824 848 662 857  41 429 422 416 801 862 107 538]

10th Percentile: 145.70000000000002
50th Percentile (Median): 532.0
90th Percentile: 848.9
First Quartile (Q1): 363.5
Third Quartile (Q3): 755.0


 66. Create a NumPy array of integers and find the index of a specific element.

In [26]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

element_to_find = 40

indices = np.where(arr == element_to_find)[0]

print("Array:", arr)
if indices.size > 0:
    print(f"Index of element {element_to_find}: {indices[0]}")
else:
    print(f"Element {element_to_find} not found in the array.")

Array: [10 20 30 40 50 60 70 80 90]
Index of element 40: 3


 67. Generate a random NumPy array and sort it in ascending order.

In [27]:
random_array = np.random.randint(1, 101, size=50)

sorted_array = np.sort(random_array)

print("Random Array:")
print(random_array)
print("\nSorted Array (Ascending Order):")
print(sorted_array)

Random Array:
[29 59 50 27 93 36 56 85 48 53 41 63 71  1 80 27 37 23 41 61 63 68 39 93
 82 20 50 18  5 16 21 48 17  8 50 24 31 51 82 56 77 20 43  6 24 16 44 86
 35 98]

Sorted Array (Ascending Order):
[ 1  5  6  8 16 16 17 18 20 20 21 23 24 24 27 27 29 31 35 36 37 39 41 41
 43 44 48 48 50 50 50 51 53 56 56 59 61 63 63 68 71 77 80 82 82 85 86 93
 93 98]


 68. Filter elements >20  in the given NumPy array.       
 arr = np.array([12, 25, 6, 42, 8, 30])

In [29]:
arr = np.array([12, 25, 6, 42, 8, 30])

filtered_elements = arr[arr > 20]

print("Original Array:")
print(arr)
print("\nFiltered Elements (greater than 20):")
print(filtered_elements)

Original Array:
[12 25  6 42  8 30]

Filtered Elements (greater than 20):
[25 42 30]


 69. Filter elements which are divisible by 3 from a given NumPy array.     
 arr = np.array([1, 5, 8, 12, 15])

In [30]:
arr = np.array([1, 5, 8, 12, 15])
filtered_elements = arr[arr % 3 == 0]

print("Original Array:")
print(arr)
print("\nFiltered Elements (divisible by 3):")
print(filtered_elements)

Original Array:
[ 1  5  8 12 15]

Filtered Elements (divisible by 3):
[12 15]


 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.    
 arr = np.array([10, 20, 30, 40, 50])

In [31]:
arr = np.array([10, 20, 30, 40, 50])
filtered_elements = arr[(arr >= 20) & (arr <= 40)]

print("Original Array:")
print(arr)
print("\nFiltered Elements (20 <= x <= 40):")
print(filtered_elements)

Original Array:
[10 20 30 40 50]

Filtered Elements (20 <= x <= 40):
[20 30 40]


 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.      
 arr = np.array([1, 2, 3])

In [32]:
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print("Array:", arr)
print("Byte Order:", byte_order)

Array: [1 2 3]
Byte Order: =


72. For the given NumPy array, perform byte swapping in place using `byteswap()`.      
 arr = np.array([1, 2, 3], dtype=np.int32) 

In [33]:
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:", arr)

arr.byteswap(inplace=True)

print("Byte-Swapped Array:", arr)

Original Array: [1 2 3]
Byte-Swapped Array: [16777216 33554432 50331648]


 73. For the given NumPy array, swap its byte order without modifying the original array using 
`newbyteorder()`.     
 arr = np.array([1, 2, 3], dtype=np.int32)

In [34]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original Array:", arr)

byte_swapped_arr = arr.newbyteorder()

print("Byte-Swapped Array:", byte_swapped_arr)

Original Array: [1 2 3]
Byte-Swapped Array: [16777216 33554432 50331648]


 74. For the given NumPy array and swap its byte order conditionally based on system endianness using 
`newbyteorder()`.     
 arr = np.array([1, 2, 3], dtype=np.int32)

In [35]:
import sys
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original Array:", arr)

system_byte_order = sys.byteorder

if arr.dtype.byteorder != system_byte_order:
    byte_swapped_arr = arr.newbyteorder()
    print("Byte-Swapped Array:", byte_swapped_arr)
else:
    print("No byte swapping needed.")

Original Array: [1 2 3]
Byte-Swapped Array: [16777216 33554432 50331648]


 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
attribute `byteorder`.      
 arr = np.array([1, 2, 3], dtype=np.int32)

In [36]:
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:", arr)

if arr.dtype.byteorder == sys.byteorder[0]:
    print("No byte swapping necessary.")
else:
    print("Byte swapping is necessary.")

Original Array: [1 2 3]
Byte swapping is necessary.


 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [37]:
arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[0] = 99  # Change the first element to 99

print("Original Array (arr1):", arr1)
print("Modified Copy Array (copy_arr):", copy_arr)

Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified Copy Array (copy_arr): [99  2  3  4  5  6  7  8  9 10]


 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [38]:
matrix = np.random.randint(1, 11, size=(3, 3))

print("Original Matrix:")
print(matrix)

view_slice = matrix[1:, 1:]

print("\nExtracted Slice:")
print(view_slice)

view_slice[0, 0] = 99

print("\nModified Slice:")
print(view_slice)
print("\nModified Matrix:")
print(matrix)

Original Matrix:
[[ 6  7  5]
 [ 2  8 10]
 [ 1  2  8]]

Extracted Slice:
[[ 8 10]
 [ 2  8]]

Modified Slice:
[[99 10]
 [ 2  8]]

Modified Matrix:
[[ 6  7  5]
 [ 2 99 10]
 [ 1  2  8]]


 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [39]:
array_a = np.arange(1, 13).reshape(4, 3)

print("Original Array (array_a):")
print(array_a)

view_b = array_a[1:, 1:] 

print("\nExtracted Slice (view_b):")
print(view_b)

view_b += 5

print("\nModified Slice (view_b):")
print(view_b)
print("\nOriginal Array After Modification (array_a):")
print(array_a)

Original Array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Extracted Slice (view_b):
[[ 5  6]
 [ 8  9]
 [11 12]]

Modified Slice (view_b):
[[10 11]
 [13 14]
 [16 17]]

Original Array After Modification (array_a):
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]


 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
reflects changes in the original `orig_array`.

In [41]:
orig_array = np.arange(1, 9).reshape(2, 4)

print("Original Array (orig_array):")
print(orig_array)

reshaped_view = orig_array.reshape(4, 2)

print("\nReshaped View (reshaped_view):")
print(reshaped_view)

reshaped_view[0, 0] = 99

print("\nModified Reshaped View (reshaped_view):")
print(reshaped_view)
print("\nOriginal Array After Modification (orig_array):")
print(orig_array)

Original Array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]

Reshaped View (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified Reshaped View (reshaped_view):
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]

Original Array After Modification (orig_array):
[[99  2  3  4]
 [ 5  6  7  8]]


 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [42]:
data = np.random.randint(1, 11, size=(3, 4))

print("Original Array (data):")
print(data)

data_copy = data[data > 5].copy()

print("\nCopied Array (data_copy):")
print(data_copy)

if data_copy.size > 0: 
    data_copy[0] = 99  

print("\nModified Copied Array (data_copy):")
print(data_copy)
print("\nOriginal Array After Modification (data):")
print(data)

Original Array (data):
[[ 5  7  5 10]
 [10  4 10  4]
 [ 4 10  7 10]]

Copied Array (data_copy):
[ 7 10 10 10 10  7 10]

Modified Copied Array (data_copy):
[99 10 10 10 10  7 10]

Original Array After Modification (data):
[[ 5  7  5 10]
 [10  4 10  4]
 [ 4 10  7 10]]


 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
operations between them.

In [43]:
A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

C_add = A + B

C_sub = A - B

print("\nAddition of A and B (C_add):")
print(C_add)
print("\nSubtraction of A and B (C_sub):")
print(C_sub)

Matrix A:
[[3 9 4]
 [6 6 5]
 [1 7 7]]

Matrix B:
[[3 4 9]
 [7 3 4]
 [5 3 4]]

Addition of A and B (C_add):
[[ 6 13 13]
 [13  9  9]
 [ 6 10 11]]

Subtraction of A and B (C_sub):
[[ 0  5 -5]
 [-1  3  1]
 [-4  4  3]]


 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [45]:
C = np.random.randint(1, 11, size=(3, 2))

D = np.random.randint(1, 11, size=(2, 4))

print("Matrix C (3x2):")
print(C)
print("\nMatrix D (2x4):")
print(D)

result = np.dot(C, D)

# Alternatively, you can use the @ operator
# result = C @ D
print("\nResult of Matrix Multiplication (C @ D):")
print(result)

Matrix C (3x2):
[[ 8  6]
 [ 7  4]
 [10  9]]

Matrix D (2x4):
[[3 7 8 9]
 [3 9 3 7]]

Result of Matrix Multiplication (C @ D):
[[ 42 110  82 114]
 [ 33  85  68  91]
 [ 57 151 107 153]]


 83. Create a matrix `E` and find its transpose.

In [46]:
E = np.random.randint(1, 11, size=(3, 4))

print("Original Matrix E:")
print(E)

E_transpose = E.T

print("\nTransposed Matrix E:")
print(E_transpose)

Original Matrix E:
[[2 8 9 3]
 [9 5 9 6]
 [3 5 2 7]]

Transposed Matrix E:
[[2 9 3]
 [8 5 5]
 [9 9 2]
 [3 6 7]]


 84. Generate a square matrix `F` and compute its determinant.

In [47]:
F = np.random.rand(3, 3)

print("Matrix F:")
print(F)

determinant_F = np.linalg.det(F)

print("\nDeterminant of Matrix F:")
print(determinant_F)

Matrix F:
[[0.90002885 0.63571461 0.00405042]
 [0.15363879 0.23142285 0.12030952]
 [0.14792512 0.67073833 0.74508633]]

Determinant of Matrix F:
0.021382596414977396


 85. Create a square matrix `G` and find its inverse.

In [48]:
G = np.random.rand(3, 3)

print("Matrix G:")
print(G)

inverse_G = np.linalg.inv(G)

print("\nInverse of Matrix G:")
print(inverse_G)

Matrix G:
[[0.63316645 0.23309997 0.47309703]
 [0.70648601 0.24386898 0.80425489]
 [0.78386729 0.30657174 0.2217572 ]]

Inverse of Matrix G:
[[-326.14378789  158.167462    122.16380085]
 [ 802.74533045 -390.45336466 -296.50628368]
 [  43.08502265  -19.30188598  -17.40534258]]
